services:
  - type: web
    name: tvapp-backend
    env: docker
    buildCommand: "npm install"
    startCommand: "npm start"
    rootDir: tvapp-backend
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase: # Use the database name defined below
          name: tvapp-db
          property: connectionString
  - type: pserv
    name: tvapp-db
    databaseName: tvapp_db
    region: frankfurt
    plan: free
    ipAllowList: [] # You can restrict access here if needed
